apiVersion: apps/v1
kind: Deployment
metadata:
  name: q6-app
  labels: 
    app: q6-app
spec:
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: q6-app
  template:
    metadata:
      labels:
        app: q6-app
    spec:
      containers:
        - image: leenavarghese/q1:1.0
          name: q6-app
        
