apiVersion: apps/v1
kind: Deployment
metadata:
  name: q2-app
  labels: 
    app: q2-app
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: q2-app
  template:
    metadata:
      labels:
        app: q2-app
    spec:
      containers:
        - image: leenavarghese/q1:1.0
          name: q2-app
        
